version: "3.6"

services: 
    wika_app:
        container_name: wika_app
        build: 
            context: .
            dockerfile: Dockerfile
        labels: 
            - traefik.enable=true
            - traefik.backend=wika_app
            - traefik.http.routers.wika_app.rule=Host(`wika.dedekrnwan.site`)
            - traefik.http.services.wika_app.loadbalancer.server.port=80
            - traefik.docker.network=proxy
            - traefik.http.routers.wika_app.entrypoints=http
        networks: 
            - proxy
networks: 
  proxy:
    external: 
      name: proxy 